export { getDatabase, closeDatabase } from './connection'
export { initSchema } from './schema'
export { BaseDAO } from './dao/base-dao'
export { topicDAO } from './dao/topic-dao'
export { contentDAO } from './dao/content-dao'
export { scheduleDAO } from './dao/schedule-dao'
export { modelConfigDAO } from './dao/model-config-dao'
export { assistantRoleDAO } from './dao/assistant-role-dao'
export { assistantConversationDAO } from './dao/assistant-conversation-dao'
export { assistantMessageDAO } from './dao/assistant-message-dao'
export { assistantDocumentDAO } from './dao/assistant-document-dao'
export { promptTemplateDAO } from './dao/prompt-template-dao'
export { appPreferenceDAO } from './dao/app-preference-dao'
export { materialDAO } from './dao/material-dao'
export { scriptDAO } from './dao/script-dao'
export { assistantDAO } from './dao/assistant-dao'
export { versionDAO } from './dao/version-dao'
export { scheduleTemplateDAO } from './dao/schedule-template-dao'
export { platformAccountDAO } from './dao/platform-account-dao'
export { generationLogDAO } from './dao/generation-log-dao'
export { customSkillDAO } from './dao/custom-skill-dao'
export { hotspotDAO } from './dao/hotspot-dao'
export { writingStyleDAO } from './dao/writing-style-dao'
export { metricsDAO } from './dao/metrics-dao'
export type { TopicRow, TopicCreateInput, TopicUpdateInput } from './dao/topic-dao'
